#include "communication/WcppTelemetry.h"
#include "packet.h"
#include <string.h>
#include <math.h>
namespace WcppTelemetry {
static size_t finish(wcpp::Packet&p,uint8_t*b,size_t c,bool ok){if(!ok)return 0;uint8_t n=p.size();if((size_t)n+1>c||n>=250)return 0;b[0]=n+1;b[n]=wcpp::Packet::checksum(b,n);return n+1;}
size_t encode(const CanSatData_t&d,uint8_t*b,size_t c,bool minimal){if(!b||c<32||c>255)return 0;memset(b,0,c);auto p=wcpp::Packet::empty(b,(uint8_t)c);p.telemetry(PACKET_ID,COMPONENT_ID);bool ok=true;
ok&=p.append("TI").setFloat64(d.sys.timestamp/1000.0);ok&=p.append("ST").setInt(d.sys.phase);ok&=p.append("SS").setInt(d.sys.subphase);ok&=p.append("MO").setInt(d.sys.operation_mode);ok&=p.append("RS").setInt(d.sys.reset_reason);ok&=p.append("BT").setFloat32(d.sys.battery_voltage);ok&=p.append("FR").setInt(d.sys.failsafe_reason);ok&=p.append("LA").setFloat64(d.gnss.latitude);ok&=p.append("LO").setFloat64(d.gnss.longitude);ok&=p.append("SA").setInt(d.gnss.satellites);if(minimal)return finish(p,b,c,ok);
ok&=p.append("AL").setFloat32(d.baro.altitude);ok&=p.append("PR").setFloat32(d.baro.pressure);ok&=p.append("TE").setFloat32(d.baro.temperature);ok&=p.append("AX").setFloat32(d.imu.ax);ok&=p.append("AY").setFloat32(d.imu.ay);ok&=p.append("AZ").setFloat32(d.imu.az);ok&=p.append("GX").setFloat32(d.imu.gx);ok&=p.append("GY").setFloat32(d.imu.gy);ok&=p.append("GZ").setFloat32(d.imu.gz);ok&=p.append("MX").setFloat32(d.mag.mx);ok&=p.append("MY").setFloat32(d.mag.my);ok&=p.append("MZ").setFloat32(d.mag.mz);ok&=p.append("HD").setFloat32(d.mag.heading);ok&=p.append("IV").setBool(d.imu.is_valid);ok&=p.append("MV").setBool(d.mag.is_valid);ok&=p.append("BV").setBool(d.baro.is_valid);ok&=p.append("NV").setBool(d.gnss.is_valid);ok&=p.append("FX").setBool(d.gnss.fix);ok&=p.append("GC").setBool(d.sys.goal_configured);ok&=p.append("GL").setFloat64(d.sys.goal_latitude);ok&=p.append("GO").setFloat64(d.sys.goal_longitude);ok&=p.append("GD").setFloat32(d.sys.goal_distance_m);ok&=p.append("MC").setInt(d.sys.motor_state);ok&=p.append("PS").setInt(d.sys.separation_status);return finish(p,b,c,ok);}
bool decodeCommand(const uint8_t*b,size_t n,Command&c){if(!b||n<5||n>250||b[0]!=n||wcpp::Packet::checksum(b,n-1)!=b[n-1])return false;auto p=wcpp::Packet::decode(b);if(!p.isCommand())return false;auto a=p.find("AC");if(a==p.end()||!(*a).isInt())return false;c.action=(uint8_t)(*a).getUInt();if(c.action==(uint8_t)MissionCommand::SET_GOAL_COORDINATE){auto la=p.find("GL"),lo=p.find("GO");if(la==p.end()||lo==p.end()||!(*la).isFloat64()||!(*lo).isFloat64())return false;c.hasGoalCoordinate=true;c.goalLatitude=(*la).getFloat64();c.goalLongitude=(*lo).getFloat64();}return true;}
bool decodeAction(const uint8_t*b,size_t n,uint8_t&a){Command c;if(!decodeCommand(b,n,c))return false;a=c.action;return true;}
}
